workflows:
  ios-chordswiper:
    name: ChordSwiper iOS Build (no Pods)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "ChordSwiper.xcodeproj"   # <-- jouw project
        XCODE_SCHEME: "ChordSwiper"              # controleer of dit exact je scheme-naam is
      xcode: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Build IPA (pure xcodeproj)
        script: |
          xcodebuild -project "$CM_BUILD_DIR/ChordSwiper.xcodeproj" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -allowProvisioningUpdates \
                     -archivePath build/ChordSwiper.xcarchive \
                     archive

          xcodebuild -exportArchive \
                     -archivePath build/ChordSwiper.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath build/ipa \
                     -allowProvisioningUpdates

    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - jouw@email.com   # vervang door je eigen mailadres
        notify:
          success: true
          failure: true
